---
- hosts: localhost
  vars:
    repo_url: git@github.com:vkhodor/cleverview.git

  tasks:
    - name: Create .ssh directory
      file:
        path: '{{ ansible_env.HOME }}/.ssh'
        mode: '0700'
        state: directory

    - name: 'Install id_rsa'
      copy:
        src: files/ssh/id_rsa
        dest: '{{ ansible_env.HOME }}/.ssh'
        mode: '0600'

    - name: 'Install id_rsa.pub'
      copy:
        src: files/ssh/id_rsa.pub
        dest: '{{ ansible_env.HOME }}/.ssh/id_rsa.pub'
        mode: '0644'

    - name: 'Install required software'
      apt:
        name:
          - dhcpcd5
          - chrony
          - nginx
          - uwsgi
          - python3
          - python3-pip
          - git
          - sqlite3
          - vim
          - snmpd
        state: present
        force_apt_get: yes

    - name: 'Enable SNMPd'
      systemd:
        name: snmpd
        enabled: true
        state: started

    - name: 'Clone/Update repo'
      git:
        repo: '{{ repo_url }}'
        dest: '/tmp/cleverview'
        clone: true
        update: true
        accept_hostkey: true
        version: '{{ version }}'

    - name: Find all .git files
      find:
        patterns: '.git*'
        paths: '/tmp/cleverview'
        recurse: true
      register: git_files

    - name: Find all TODO files
      find:
        patterns: 'TODO*'
        paths: '/tmp/cleverview'
        recurse: true
      register: todo_files


    - name: Find all sqlite files
      find:
        patterns: '*.sqlite'
        paths: '/tmp/cleverview'
        recurse: true
      register: sqlite_files

    - name: Remove all found files
      file:
        path: '{{ item }}'
        state: absent
      with_items: '{{ git_files.files + todo_files.files + sqlite_files.files }}'

    - name: Remove some files
      file:
        path: '/tmp/cleverview/{{ item }}'
        state: absent
      with_items:
        - migrations
        - update.sh
        - deploy

    - name: Upgrade pip3
      shell: pip3 install --upgrade pip
      changed: false

    - name: Install python packages
      pip:
        requirements: /tmp/cleverview/requirements.txt

    - name: 'Configure Nginx'
      block:
        - name: Copy nginx.conf
          copy:
            src: files/nginx.conf
            dest: /etc/nginx/nginx.conf
            owner: root
            group: root
            mode: '0644'

        - name: Copy cleverview-ui.conf
          copy:
            src: files/cleverview-ui.conf
            dest: /etc/nginx/sites-available/cleverview-ui.conf

        - name: Remove default site
          file:
            path: /etc/nginx/sites-enabled/default
            state: absent

        - name: Create /run/uwsgi directory
          file:
            path: /run/uwsgi
            state: directory

        - name: Enable cleverview-ui site
          file:
            src: /etc/nginx/sites-available/cleverview-ui.conf
            dest: /etc/nginx/sites-enabled/cleverview-ui.conf
            state: link

        - name: Restart and enable nginx
          systemd:
            name: nginx
            enabled: true
            state: restarted

#    - name: 'Configure WebGUI Service'
#      block:
#        - name: 'copy unit file'
#          copy:
#            src: webgui.service
#            dest: /etc/systemd/system/webgui.service
#
#        - name: 'enable webgui service'
#          shell: systemctl enable webgui
#
#        - name: 'start webgui service'
#          service:
#            name: webgui
#            state: restarted
#
#    - name: Configure modbus-client
#      block:
#        - name: copy unit
#          copy:
#            src: modbus-client.service
#            dest: /etc/systemd/system/modbus-client.service
#
#        - name: reload systemd units
#          shell: systemctl daemon-reload
#
#        - name: enable modbus-client.service
#          shell: systemctl enable modbus-client
#
#        - name: start modbus-client
#          service:
#            name: modbus-client
#            state: restarted
#
#    - name: 'Configure modbus-connector Service'
#      block:
#        - name: 'disable modbus-connector'
#          shell: update-rc.d modbus-connector disable || exit 0
#
#        - name: 'remove old modbus-connector start script'
#          file:
#            path: /etc/init.d/modbus-connector
#            state: absent
#
#        - name: 'remove cronjob for data-cleaner.py'
#          cron:
#            name: 'data-cleaner job'
#            job: 'cd /root/snmpagg/modbus-connector/; ./data-cleaner.py > /tmp/data-clear.log'
#            state: absent
#
#    - name: 'Sync FS'
#      shell: sync
#
#    - name: 'Add cronjob real time clock syncronization every week'
#      cron:
#        name: 'real time clock syncronization every week'
#        job: '/sbin/hwclock -s'
#        hour: '1'
#        minute: '2'
#        weekday: '1'
#
#    - name: Add Debian-snmp to root group
#      user:
#        name: 'Debian-snmp'
#        groups: 'root'
#        append: yes
#
#    - name: Add group permisions
#      file:
#        path: '/root'
#        mode: 0755
